local Observable = require("reactivex/observable")
local Observer = require("reactivex/observer")
local Subscription = require("reactivex/subscription")
local Subject = require("reactivex/subjects/subject")

require('reactivex/operators/concat')

describe('concat', function()
  it('produces an error if its parent errors', function()
    expect(Observable.throw():concat()).to.produce.error()
  end)

  it('returns the first argument if it is the only argument', function()
    local observable = Observable.fromRange(1, 3):concat()
    expect(observable).to.produce(1, 2, 3)
  end)

  it('waits until one observable completes before producing items from the next', function()
    local subjectA = Subject.create()
    local subjectB = Subject.create()
    local onNext, onError, onCompleted = observableSpy(Observable.concat(subjectA, subjectB))
    subjectA:onNext(1)
    subjectB:onNext(2)
    subjectA:onNext(3)
    subjectA:onCompleted()
    subjectB:onNext(4)
    subjectB:onNext(5)
    subjectB:onCompleted()
    expect(onNext).to.equal({{1}, {3}, {4}, {5}})
    expect(#onError).to.equal(0)
    expect(#onCompleted).to.equal(1)
  end)

  it('should error if any of the sources error', function()
    local badObservable = Observable.create(function(observer) observer:onError('oh no') end)
    local observable = Observable.of(1):concat(Observable.of(2), badObservable)
    expect(observable).to.produce.error()
  end)

  it('should complete once the rightmost observable completes', function()
    local subject = Subject.create()
    local onCompleted = spy()
    local observable = Observable.concat(Observable.fromRange(1, 5), Observable.fromRange(1, 5), subject)
    observable:subscribe(nil, nil, onCompleted)
    expect(#onCompleted).to.equal(0)
    subject:onCompleted()
    expect(#onCompleted).to.equal(1)
  end)
end)
