local Observable = require("reactivex/observable")
local Observer = require("reactivex/observer")
local Subscription = require("reactivex/subscription")
local Subject = require("reactivex/subjects/subject")

require('reactivex/operators/takeUntil')

describe('takeUntil', function()
  it('produces an error if its parent errors', function()
    local trigger = Observable.create(function() end)
    createSingleUseOperator(
      "simulateError", 
      function (destination)
        destination:onError()
      end
    )
    local observable = Observable.of(''):simulateError()
    expect(observable).to.produce.error()
    expect(observable:takeUntil(trigger)).to.produce.error()
  end)

  it('fails if the first argument is not an Observable', function()
    local observable = Observable.of(3)
    expect(observable:takeUntil(nil)).to.fail()
    expect(observable:takeUntil(0)).to.fail()
    expect(observable:takeUntil({})).to.fail()
  end)

  it('produces all values if the specified observable does not produce any values', function()
    local trigger = Observable.create(function() end)
    local observable = Observable.fromTable({2, 3, 4}):takeUntil(trigger)
    expect(observable).to.produce(2, 3, 4)
  end)

  it('produces values after the specified observable produces a value', function()
    local onNext = spy()
    local trigger = Subject.create()
    local subject = Subject.create()
    subject:takeUntil(trigger):subscribe(Observer.create(onNext))
    subject:onNext('a')
    subject:onNext('b')
    trigger:onNext('a')
    subject:onNext('c')
    subject:onNext('d')
    subject:onCompleted()
    expect(onNext).to.equal({{'a'}, {'b'}})
  end)

  it('produces no values if the specified observable fires immediately', function()
    local onNext = spy()
    local subject = Subject.create()
    subject:takeUntil(Observable.of(1)):subscribe(Observer.create(onNext))
    subject:onNext(1)
    subject:onNext(2)
    subject:onNext(3)
    subject:onCompleted()
    expect(onNext).to.equal({})
  end)
end)
